<?php
namespace mvbplugins\extmedialib;

defined( 'ABSPATH' ) || die( 'Not defined' );

add_filter('intermediate_image_sizes_advanced', 'mvbplugins\extmedialib\image_subsizes_filter', 10, 3);
add_filter('wp_unique_filename', 'mvbplugins\extmedialib\wp_unique_filename_filter', 10, 6);

/**	
 * filter the image sizes to be created by WP
 * @param array $newsizes the registered image subsizes as provided by get_registered_subsizes
 * @param array $image_meta the imagemetadata with sizes
 * @param int $wp_id the wp id of the attachment
 *
 * @return array $newsizes	if this is empty no subsizes will be created by _wp_make_subsizes()
 */
function image_subsizes_filter(array $newsizes, array $image_meta, int $wp_id) : array {
	// get filename from $image_meta
    $orig_newsizes = $newsizes;
	$file = $image_meta["file"];
	$expectedSizes = generate_wp_image_subsizes($file, $newsizes); // use wp_unique_filename to generate the expected filenames for the subsizes. This is necessary because the filename can be changed by WP if a file with the same name already exists in the upload directory. The expected filenames are generated based on the original filename and the size name, width, height and crop settings of the subsizes.
    if ( empty( $expectedSizes ) ) {
        return $newsizes;
    }

	foreach ( $newsizes as $new_size_name => $new_size_data ) {
		// generate the expected image filename for the subsizes from array $newsizes respecting the WP standards for width, height and crop
        /** @var array{file: string, width: int, height: int, 'mime-type': string, filesize: int, exists: bool, crop: bool} $new_size_meta */
        $new_size_meta = $expectedSizes[ $new_size_name ]; 

		if ( isset( $new_size_meta['exists'] ) && $new_size_meta['exists'] ) {
			// Save the size meta value.
			unset( $new_size_meta['exists'] );
            unset( $new_size_meta['crop'] );
            unset( $new_size_meta['exists'] );

			$image_meta['sizes'][ $new_size_name ] = $new_size_meta; // file, real width, real height, mime-type, filesize
            wp_update_attachment_metadata( $wp_id, $image_meta ); //This is called for each subsizes, so it is the same like WordPress does it.
			
            unset($newsizes[ $new_size_name ]); 
		}
	}
    // only update if all subsizes are available. Skip if some subsizes are missing. 
    if ( empty( $newsizes ) ) {
        // if all subsizes are available the metadata is updated with the new subsizes and the subsizes will not be created by _wp_make_subsizes() because newsizes is empty.
        //wp_update_attachment_metadata( $wp_id, $image_meta );
        return $newsizes;
    } else {
        // if only some subsizes are missing the metadata is not created correctly because the missing subsizes will be created by _wp_make_subsizes() but the existing subsizes will not be included in the metadata because they are not created by _wp_make_subsizes() and the metadata is not updated with the existing subsizes. So in this case we return the original newsizes to let WP create all subsizes and update the metadata correctly.
        return $orig_newsizes;
    }
}

/**
 * filter wp_unique_filename : check if files that contain the same filename already exist in the upload directory. This runs before the file is actually moved to the upload directory.
 * So, functions on the new file have to done with the tmp-file given by $_FILES (currently unused as not required)
 * 
 * @param string $filename the filename generated by WP's wp_unique_filename function, which may include a suffix if a file with the same name already exists.
 * @param string $ext the file extension of the uploaded file.
 * @param string $dir the full path to the upload directory where the file will be stored.
 * @param callable $unique_filename_callback a callback function that can be used to generate a unique filename if needed.
 * @param array $alt_filenames an array of alternative filenames that have been tried so far.
 * @param string|int $number a number that is appended to the filename if a file with the same name already exists (e.g., -1, -2, etc.).
 *
 * @return string $new_filename	the original filename without suffix if this is a replacement upload and all expected subsizes already exist in the upload directory, otherwise return the original $filename generated by WP.
 */
function wp_unique_filename_filter( string $filename, string $ext, string $dir, ?callable $unique_filename_callback, ?array $alt_filenames, string|int $number) : string {
    // 1. Only act if WP added a suffix
    if (empty($number) || (int)$number === 0) {
        return $filename;
    }

    // 2. Only images
    $allowed_ext = ['.jpg', '.jpeg', '.png', '.webp', '.avif'];
    if (!in_array(strtolower($ext), $allowed_ext, true)) {
        return $filename;
    }

    // 3. Extract base name safely (remove "-n")
    $pathinfo = pathinfo($filename);
    if (!preg_match('/^(.*)-(\d+)$/', $pathinfo['filename'], $matches)) {
        return $filename;
    }
    $base_name = $matches[1];
    $original_filename = $base_name . $ext;

    // 4. Normalize dir
    $dir = trailingslashit($dir);
    $original_fullpath = $dir . $original_filename;

    // 5. If original exists → keep suffix (safety)
    if (is_file($original_fullpath)) {
        return $filename;
    }

    // 6. Get and cout registered subsizes
    $subsizes = wp_get_registered_image_subsizes();

    if (empty($subsizes)) {
        return $filename;
    }
    $expected_count = count($subsizes);

    // 7. Find existing subsizes via glob (fast)
    $pattern = $dir . $base_name . '-*x*' . $ext;
    $files = glob($pattern);

    if ($files === false) {
        return $filename;
    }

    // 8. Filter only valid "-WxH" matches (avoid false positives)
    $valid_subsizes = [];
    $regex = sprintf( '/^%s-\d+x\d+%s$/i', preg_quote($base_name, '/'), preg_quote($ext, '/') );
    foreach ($files as $file) {
        $basename = basename($file);

        if (preg_match($regex, $basename)) {
            // check if the file was created in the last 5 minutes to avoid picking up old subsizes from previous uploads.
            $file_time = filemtime($file);
            if (time() - $file_time > 300) {
                continue;
            }
            $valid_subsizes[] = $file;
        }
    }
    $found_count = count($valid_subsizes);

    // 9. Optional: consider scaled image as additional "subsize"
    /*
    $scaled_exists = is_file($dir . $base_name . '-scaled' . $ext);
    if ($scaled_exists) {
        $found_count++;
        $expected_count++; // treat as expected variant
    }
    */

    // 10. Strict comparison
    if ($found_count !== $expected_count) {
        return $filename;
    }

    // 11. Respect WP collision detection
    if (!empty($alt_filenames) && in_array($original_filename, $alt_filenames, true)) {
        return $filename;
    }

    //All subsizes accounted for → remove suffix
    return $original_filename;
}

/**
 * Generates the expected image filenames and filepaths as string for the subsizes from the array newsizes
 * "crop" is a boolean that decides wether the image should be cropped or not. If crop is true the new filename (and dimensions) will be exactly cropped to width and heigt.
 * If crop is false the larger value of the image (be it width or height respecting orientation) will remain unchanged and the shorter value (be it height or width respecting orientation) will be set according to the aspect ratio.
 * @param mixed $original_path the original image path relative to the upload directory.
 * @param mixed $newsizes   the array of subsizes
 * @return array{exists: bool, file: string, filesize: int, height: int, mime-type: bool|string, width: int[], crop: bool}
 */
function generate_wp_image_subsizes(string $original_path, array $newsizes) : array {
    $info = pathinfo($original_path);
    $ext = $info['extension'];
    $name = $info['filename']; // remove the '-scaled' suffix if it exists.
    if (str_ends_with($name, '-scaled')) {
        $name = substr($name, 0, -7);
    }
    $dir = $info['dirname'];
    $subsizes = [];

    // Check if unscaled file exists
    if ( !is_file($original_path) ) {
        $testdir = wp_get_upload_dir()["basedir"];
        $testpath = $testdir . DIRECTORY_SEPARATOR . $original_path;
        // sanitize the path from double slashes and backslashes for consistent processing.
        $testpath = str_replace(['//', '\\', '\/', '/\\'], DIRECTORY_SEPARATOR, $testpath);

        // correct the path to the original file if it is not completely given. So the file shall be uploaded before.
        if (is_file($testpath)) {
            $original_path = $testpath;
            $dir = $testdir . DIRECTORY_SEPARATOR . $dir;
            #error_log('relative path corrected to: ' . $original_path);
        } else {
            #error_log("generate_wp_image_subsizes: original_path: " . $original_path . " does not exist");
            return $subsizes;
        }
    }
    #error_log("generate_wp_image_subsizes: original_path: " . $original_path);
    // get image dimensions from $original_file
	$size = wp_getimagesize($original_path);

    if ( !is_array($size)) {
        return $subsizes;
    } elseif ( !isset($size[0]) || !isset($size[1]) || $size[0] == 0 || $size[1] == 0 ) {
        return $subsizes;
    }
	$origWidth = $size[0];
	$origHeight = $size[1];
	$aspRatio = $origWidth / $origHeight;
    
    foreach ($newsizes as $size_name => $size) {
        $width = isset($size['width']) ? (int)$size['width'] : 0;
        $height = isset($size['height']) ? (int)$size['height'] : 0;
        $crop = isset($size['crop']) ? (bool)$size['crop'] : false;
        
        // Build the suffix based on crop setting
        if ($crop && $width>0 && $height>0) {
            // Exact dimensions for cropped images
            $suffix = "{$width}x{$height}";
        } elseif ( !$crop ) {
            // Only the max dimension for scaled images
            if ($width >= $height && !($width == 0 || $width == 9999)) {
				// landscape orientation
				$calcHeight = (int)round($width / $aspRatio );
				$suffix = "{$width}x{$calcHeight}";
                $height = $calcHeight; // update height for later use
            } elseif (!($height == 0 || $height == 9999)) {
				// portrait orientation
				$calcWidth = (int)round($height * $aspRatio );
				$suffix = "{$calcWidth}x{$height}";
                $width = $calcWidth; // update width for later use
            } elseif ($width == 0 || $width == 9999) {
                $calcWidth = (int)round($height * $aspRatio);
                $suffix = "{$calcWidth}x{$height}";
                $width = $calcWidth; // update width for later use
            } elseif ($height == 0 || $height == 9999) {
                $calcHeight = (int)round($width / $aspRatio);
                $suffix = "{$width}x{$calcHeight}";
                $height = $calcHeight; // update height for later use
            } else {
                $suffix = 'wrong';
            }
        }
        // check here for changed mime-type 
        $new_filename = $name . '-' . $suffix . '.' . $ext;
        $new_filepath = $dir . DIRECTORY_SEPARATOR . $new_filename;

        // check the OS running on the server
        if (strtoupper(substr(PHP_OS, 0, 3)) === 'WIN') {
            // Windows
            $new_filepath = str_replace('/', '\\', $new_filepath);
        }
        
		$fileexists = is_file($new_filepath); // works only for the initial upload of an image.
        
        // Check if file exists as renamed *.oldimagefile and if so rename it to the expected name. But only if the updated subsize file was uploaded before.
        $subsizeUploadedBefore = array_key_exists('subsizesuploaded', $_GET) && $_GET['subsizesuploaded'] == 'true';
        
        if ( !$fileexists && $subsizeUploadedBefore ) { // check that the file was uploaded before
            $old_filepath = $new_filepath . '.oldimagefile';
            if (is_file($old_filepath)) {
                rename($old_filepath, $new_filepath);
                $fileexists = true;
            }
        }
        #error_log( "generate_wp_image_subsizes: " . $new_filepath . " exists: " . strval($fileexists) );
        
        $subsizes[$size_name] = array(
            'file' => $new_filename,
            'width' => $width,
            'height' => $height,
			'mime-type' => $fileexists ? wp_get_image_mime($new_filepath) : '',
			'filesize' => $fileexists ? wp_filesize($new_filepath) : 0,
			# additional fields
			'exists' => $fileexists,
            'crop' => $crop
        );
    }
    
    return $subsizes;
}